[project]
name = "api"
version = "0.1.0"
description = "Mi API con FastAPI"
dependencies = [
    "fastapi[standard]",
    "pydantic",
    "python-dotenv",
    "supabase"
]

[tool.fastapi]
entrypoint = "main:app"

[tool.setuptools]
packages = ["models"] # O puedes usar find con un exclude, pero listar tus paquetes de python es lo más limpio